api:
  dashboard: true
  insecure: true  # segura para uso local

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: localresolver

providers:
  docker:
    exposedByDefault: false  # só expõe containers com label traefik.enable=true

certificatesResolvers:
  localresolver:
    acme:
      email: local@localhost
      storage: /acme.json
      # O Let's Encrypt não será usado, mas deixamos o resolver configurado.
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem
